const TABLE_NAME = 'PATIENTS';
const COL_DOCUMENT = 'document';
const COL_STRATUM = 'stratum';
const COL_ADITIONAL_INFORMATION = 'aditional information';
const COL_DECEASED = 'deceased';
const COL_DECEASED_DATE = 'deceaced_date';
const COL_ID_PROFESSION = 'id_profession';

const FOREIGN_KEY_PERSON = 'per_fk_doc';
const FOREIGN_KEY_PROFESSION = 'pac_fk_idp';

const FOREIGN_TABLE_PEOPLE = 'PEOPLE';
const FOREIGN_TABLE_PROFESSION = 'PROFESSIONS';

const COL_FK_PEOPLE = 'document';
const COL_FK_PROFESSION = 'id';

export default {
  createTable: (): string => {
    return `CREATE TABLE IF NOT EXISTS ${TABLE_NAME} (${COL_DOCUMENT} TEXT PRIMARY KEY NOT NULL, 
        ${COL_STRATUM} NUMBER NOT NULL, ${COL_ADITIONAL_INFORMATION} TEXT, ${COL_DECEASED} BOOLEAN, 
        ${COL_DECEASED_DATE} DATE, ${COL_ID_PROFESSION} UUID NOT NULL,  CONSTRAINT ${FOREIGN_KEY_PERSON} FOREIGN KEY (${COL_DOCUMENT}) 
        REFERENCES ${FOREIGN_TABLE_PEOPLE}(${COL_FK_PEOPLE}), CONSTRAINT ${FOREIGN_KEY_PROFESSION} FOREIGN KEY (${COL_ID_PROFESSION}) 
        REFERENCES ${FOREIGN_TABLE_PROFESSION}(${COL_FK_PROFESSION}))`;
  },
};
